### ISSUE TITLE
A couple of issues with the Cavity element

### ISSUE THREAD

**Issue by delaossa** [ocelot-collab/ocelot#307]
Hello all,

I'd like to share a Notebook example to simulate an active energy compressor for a laser-plasma accelerator beam.
The setup is a simplification of that shown here -> https://www.nature.com/articles/s41586-025-08772-y

https://gitlab.desy.de/delaossa/energy_compressor_example/-/blob/main/EC_example.ipynb

The example works fine as it successfully compresses the energy spread of the initial beam as intended.
However, I have observed two issues:
1. There is some dispersion induced on the beam in the Cavity (see last plot in the Notebook).
2. Tracking through the Cavity fails when the phase is exactly 90 deg.

Is this normal?
The 90 deg issue can be tested by just setting `tan_phi = 0` in the example:
https://gitlab.desy.de/delaossa/energy_compressor_example/-/blob/main/EC_example_90.ipynb

Thanks for the help!

**Comment by sergey-tomin** [comment]
Hi Alberto,
thanks for the feedback.

Regarding the 90° case — yes, that was indeed a bug.
At \phi = 90^\circ the cavity produces zero net energy gain, which creates a removable singularity in several longitudinal map terms. When I originally implemented the higher-order elements, I only treated this limit properly for R56 and T566, but I overlooked the same issue in R55, T555, and T556. I have now added the correct analytic limits for all of them and removed the singularity. I’ve now added the correct limits for all of them in the Ocelot.

While fixing this, I also found another issue: when the cavity produces a negative energy gain (deceleration), the code incorrectly fell back to the drift expressions for the second-order terms. This is now corrected — the general RF formulas are applied for both positive and negative gain, and the drift limit is used only when the actual energy change tends to zero.

I still need a bit of time to run all unit tests — some may fail because the corrected maps change results in zero-crossing and decelerating cases.

Regarding the dispersion: I think I have an idea why you see this behaviour, but I need to check it more carefully.

Cheers,
Sergey.

**Comment by delaossa** [comment]
Hi Sergey!
Thank you very much for looking at this so quickly. 👍

**Comment by delaossa** [comment]
On the dispersion issue, I just did the following test starting with a beam with ~0.1% spread so everything is linear:
https://gitlab.desy.de/delaossa/energy_compressor_example/-/blob/main/EC_example_001.ipynb
Curiously, despite still getting a sizable value for the dispersion after the cavity, one doesn't really notice when looking directly at the p vs x and p vs y distributions (see last plot).
Dispersion is calculated as $D_x = \langle x p \rangle / \langle p^2 \rangle$. 
So could this quantity be "too much" amplified through the energy spread compression? 
Cheers

**Comment by sergey-tomin** [comment]
regarding problem with 90 degree phase here is fix a87cf1f088983733905964ca458f300d8a5d0fdc
regarding second issue I did not look yet

**Comment by delaossa** [comment]
I would like to share yet another example which might hint the dispersion issue in the chicane:
https://gitlab.desy.de/delaossa/energy_compressor_example/-/blob/main/EC_example_001_openD.ipynb

Here, the last dipole of the chicane is detuned by 1% such that the dispersion is not completely closed after the chicane.
Despite the dispersion is still relatively small at the cavity entrance, it gets hugely magnified by the cavity!

This suggests that the issue in the previous case with a closed dispersion might be seeded by a residual non-zero dispersion after the chicane.

Any ideas? @sergey-tomin

**Comment by sergey-tomin** [comment]
Hi,
I looked a bit deeper into this problem. It seems an interesting effect and very likely has a purely beam-physics origin. Here are a few observations:
The cavity seems indeed “amplify’’ the incoming dispersion... 
1. Case with intentionally leaked dispersion (e.g. by detuning the last dipole): 
 * Because of the chicane’s $R_{56}$, the beam has a $\tau$–p correlation (a chirp).
 * Leaking dispersion introduces an additional x–p correlation at the entrance (dispersion).
 * With the chosen cavity phase, the cavity removes most of the $\tau$–p correlation, but at the same time amplifies the transverse x–p correlation. Cavity focusing effect + chirp reduction?
 * Changing the cavity phase can reduce this correlation, but then you reintroduce some chirp.

I would say it might be worth looking more systematically into this interplay.

 2.	Case with no intentional  dispersion leakage’:
Even then, you still see a small residual dispersion. However, this just a statistics issue rather than physics: increasing the number of macroparticles (e.g. to 10e6) makes this effect disappear.

**Comment by sergey-tomin** [comment]
I looked into this a bit more yesterday. I added an EmptyProc to observe how dispersion develops inside the cavity:
```python
lat = ocl.MagneticLattice(cell, method=method, stop=None)
navi = ocl.Navigator(lat, unit_step=0.05)
navi.add_physics_proc(EmptyProc(), ms, me ) # ms and me are Markers I added to the ends of the lattice 
```
and is the results:

<img width="1644" height="850" alt="Image" src="https://github.com/user-attachments/assets/44932406-8b97-4164-8bf8-673757cd9a58" />

I don't think there is anything wrong with the tracking itself. I suspect the problem lies in how we calculate dispersion from the distribution (the method we introduced recently), though I haven't pinpointed exactly what is wrong yet. The calculation logic seems correct. Since you are working on this scheme, do you have any ideas?"

**Comment by delaossa** [comment]
Thanks Sergey for taking a look! I also think that there is nothing wrong with the tracking, but rather with the calculation of the dispersion from the array of particles.
This issue only appears when the cavity is set to maximum energy compression settings, which makes the energy spread of the beam near a factor 100 smaller than initially.
I suspect that this is what is making our calculation of the dispersion (i.e. $D_x = \langle x p \rangle / \langle p^2 \rangle$) to reach such high values.
This can be seen very well in your figure where the dispersion only explodes by the end of the propagation through the cavity when the energy spread becomes minimal.

However, I still don't know what to do about it. The statistical calculation of the dispersion seems fine for any other case and works well to correct the Twiss parameters of beams with high energy spread in high dispersion areas.

**Comment by delaossa** [comment]
I did one more test to convince me that everything is alright.
Assuming no focusing (or defocusing) through the cavity, the quantity $D_x \sigma_p$ should grow linearly as in free propagation. And it does! (bottom panel):
<img width="1469" height="1050" alt="Image" src="https://github.com/user-attachments/assets/1919d296-2487-4533-8955-e023c2c2c8b1" />

This check was suggested by @MaxThevenet after discussing the issue. Thanks!

In conclusion, perhaps the mistake was more in comparing $D_x$ as calculated from the beam statistics with that coming from the `twiss` function, which operates at a fix energy. 
This comparison normally works well when the energy spread of the beam is low and does not change much in the propagation.
Would you agree @sergey-tomin?

Updated example:
https://gitlab.desy.de/delaossa/energy_compressor_example/-/blob/main/EC_example_001_openD.ipynb
 
Thanks!
